# Generated by Django 2.1.7 on 2019-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='last_voted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
